apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ng-core
  namespace: ng-core
  labels:
    app: ng-core
spec:
  selector:
    matchLabels:
      app: ng-core
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
