apiVersion: v1
kind: Service
metadata:
  name: ng-core
  namespace: ng-core
  labels:
    app: ng-core
    version: v1
  annotations:
    description: 'ng-core application service'
spec:
  type: ClusterIP
  selector:
    app: ng-core
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
